/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inse_app;

import java.net.URL;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 * @author UP735175
 * @author UP762633
 * @author UP775061
 * @author UP759167
 * @author UP784356
 */
public class CalEventInfo extends javax.swing.JFrame {

    Mysql mysql = new Mysql("213.131.183.194", "insedb", "INSE", "INSE3B");
    String eventID = "";

    /**
     * Creates new form CalEventInfo
     *
     * @param id
     */
    public CalEventInfo(String id) {
        initComponents();
        eventID=id;
        populateGUI(id);
    }

    /**
     * Get Event info From ID
     * @param id Event ID 
     */
    private void populateGUI(String id) {
        try {
            ResultSet myRs = mysql.searchByID(id);
            while (myRs.next()) {
                //int rs_ID = myRs.getInt("ID");
                LblEmail.setText("Email:               " + myRs.getString("Email"));
                LblDate.setText("Event Date:      " + myRs.getString("EventDate"));
                LblStart.setText("Start Time:       " + myRs.getString("EventTimeStart"));
                LblEnd.setText("End Time:        " + myRs.getString("EventTimeEnd"));
                LblDesc.setText("Description:     " + myRs.getString("EventDescription"));
                LblLoc.setText("Location:          " + myRs.getString("EventLocation"));
                URL picURL;
                picURL = new URL(myRs.getString("PictureRef"));
                LblPic.setIcon(new ImageIcon(ImageIO.read(picURL)));
            }
        } catch (Exception exc) {
            exc.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPic = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblDate = new javax.swing.JLabel();
        LblStart = new javax.swing.JLabel();
        LblEnd = new javax.swing.JLabel();
        LblDesc = new javax.swing.JLabel();
        LblLoc = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblPic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        LblEmail.setText("Email:");

        LblDate.setText("Event Date:");

        LblStart.setText("Start Time:");

        LblEnd.setText("End Time:");

        LblDesc.setText("Description:");

        LblLoc.setText("Location");

        jLabel12.setText("Picture:");

        BtnDelete.setText("Delete Event");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDate)
                            .addComponent(LblStart)
                            .addComponent(LblEnd)
                            .addComponent(LblDesc)
                            .addComponent(LblLoc)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(BtnDelete))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPic)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LblEmail))
                    .addComponent(BtnDelete))
                .addGap(18, 18, 18)
                .addComponent(LblDate)
                .addGap(18, 18, 18)
                .addComponent(LblStart)
                .addGap(18, 18, 18)
                .addComponent(LblEnd)
                .addGap(18, 18, 18)
                .addComponent(LblDesc)
                .addGap(18, 18, 18)
                .addComponent(LblLoc)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPic)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        mysql.deleteByID(eventID);
        this.dispose();
    }//GEN-LAST:event_BtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblDesc;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblEnd;
    private javax.swing.JLabel LblLoc;
    private javax.swing.JLabel LblPic;
    private javax.swing.JLabel LblStart;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
