/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inse_app;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * @author UP735175
 * @author UP762633
 * @author UP775061
 * @author UP759167
 * @author UP784356
 */
public class NewAccForm extends javax.swing.JFrame {

    Mysql mysql = new Mysql("213.131.183.194", "insedb", "INSE", "INSE3B");
    boolean EmailMatch = false;
    boolean PassMatch = false;
    boolean Fname = false;
    boolean Lname = false;
    boolean Uname = false;

    /**
     * Creates new form NewAccForm
     */
    public NewAccForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        TxtFName = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        TxtLName = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        TxtUName = new javax.swing.JTextField();
        cnfmEmailLabel = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        TxtConfEmail = new javax.swing.JTextField();
        cnfmPassLabel = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        BtnSubmit = new javax.swing.JButton();
        TxtPass = new javax.swing.JPasswordField();
        TxtConfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        fNameLabel.setText("First Name:");

        lNameLabel.setText("Last Name:");

        TxtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtFNameKeyReleased(evt);
            }
        });

        usernameLabel.setText("Username:");
        usernameLabel.setToolTipText("");

        TxtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtLNameKeyReleased(evt);
            }
        });

        emailLabel.setText("Email address:");

        TxtUName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtUNameKeyReleased(evt);
            }
        });

        cnfmEmailLabel.setText("Confirm Email:");

        passLabel.setText("Password:");

        TxtConfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtConfEmailKeyReleased(evt);
            }
        });

        cnfmPassLabel.setText("Confirm Password:");

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        TxtConfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtConfPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cnfmPassLabel)
                            .addComponent(passLabel)
                            .addComponent(cnfmEmailLabel)
                            .addComponent(emailLabel)
                            .addComponent(usernameLabel)
                            .addComponent(lNameLabel)
                            .addComponent(fNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtLName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtUName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtConfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtConfPass))
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtConfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnfmEmailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(TxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnfmPassLabel)
                    .addComponent(TxtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtConfEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtConfEmailKeyReleased
        if (TxtConfEmail.getText().equals(TxtEmail.getText())) {
            TxtConfEmail.setBackground(Color.green);
            EmailMatch = true;
        } else {
            EmailMatch = false;
            TxtConfEmail.setBackground(Color.red);
        }
    }//GEN-LAST:event_TxtConfEmailKeyReleased

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        Pattern EmailVal = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
        if (EmailVal.matcher(TxtEmail.getText()).matches() == true) {
            if (Fname == true && Lname == true && Uname == true && EmailMatch == true && PassMatch == true) {
                mysql.signup(TxtFName.getText(), TxtLName.getText(), TxtUName.getText(), TxtEmail.getText(), TxtPass.getText());
                new LoginForm().setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "The entered Email Address is not valid", "Email Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void TxtFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFNameKeyReleased
        if (!TxtFName.getText().isEmpty()) {
            Fname = true;
            TxtFName.setBackground(Color.green);
        } else {
            Fname = false;
            TxtFName.setBackground(Color.red);
        }
    }//GEN-LAST:event_TxtFNameKeyReleased

    private void TxtLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLNameKeyReleased
        if (!TxtLName.getText().isEmpty()) {
            Lname = true;
            TxtLName.setBackground(Color.green);
        } else {
            Lname = false;
            TxtLName.setBackground(Color.red);
        }
    }//GEN-LAST:event_TxtLNameKeyReleased

    private void TxtUNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUNameKeyReleased
        if (!TxtUName.getText().isEmpty()) {
            Uname = true;
            TxtUName.setBackground(Color.green);
        } else {
            Uname = false;
            TxtUName.setBackground(Color.red);
        }
    }//GEN-LAST:event_TxtUNameKeyReleased

    private void TxtConfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtConfPassKeyReleased
        if (TxtConfPass.getText().equals(TxtPass.getText())) {
            TxtConfPass.setBackground(Color.green);
            PassMatch = true;
        } else {
            PassMatch = false;
            TxtConfPass.setBackground(Color.red);
        }
    }//GEN-LAST:event_TxtConfPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JTextField TxtConfEmail;
    private javax.swing.JPasswordField TxtConfPass;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFName;
    private javax.swing.JTextField TxtLName;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtUName;
    private javax.swing.JLabel cnfmEmailLabel;
    private javax.swing.JLabel cnfmPassLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
